; FILE:       churchill-england
; PURPOSE:    testing gulf analogies to WW2
; PROGRAMMER: Bobbie and Keith
; CREATED:    3-13-91
; UPDATED:    


(defun make_Gulf ()

(make_struc 'Gulf
            'sentence
            '(all
              ((country (Iraq) G1)
               (country (US) G2)
               (country (Kuwait) G3)
               (country (Saudi-Arabia) G4)
               (country (England) G5)
               (p_Iraq (Iraq) G6)
               (p_US (US) G7)
               (p_Kuwait (Kuwait) G8)
               (p_Saudi-Arabia (Saudi-Arabia) G9)
               (p_England (England) G10)
               (person (Saddam) G11)
               (person (Bush) G12)
               (person (emir-of-Kuwait) G13)
               (person (sheik-of-SA) G14)
               (person (pm-of-England) G15)
               (leader-of (Saddam Iraq) G16)
               (leader-of (Bush US) G17)
               (leader-of (emir-of-Kuwait Kuwait) G18)
               (leader-of (sheik-of-SA Saudi-Arabia) G19)
               (leader-of (pm-of-England England) G20)
; neighbor-of goes in the other to Iraq direction
               (neighbor-of (Kuwait Iraq) G21)
               (neighbor-of (Saudi-Arabia Iraq) G22)
               (weaker-than (Kuwait Iraq) G23)
               (weaker-than (Saudi-Arabia Iraq) G24)
               (weaker-than (Iraq US) G25)
; ally-of goes in the weak to strong direction
               (ally-of (England US) G26)
;               (ally-of (US England) G27) 
               (ally-of (Saudi-Arabia US) G28)
;               (ally-of (US Saudi-Arabia) G29)
               (ally-of (Kuwait US) G30)
;               (ally-of (US Kuwait) G31)
; presume saddam=hitler so don't need this
;               (dictator-of (Saddam Iraq) G32)
               (militarize (Saddam Iraq) G33)
               (occupy (Iraq Kuwait) G34)
; kjh not like
;               (take-first (Iraq Kuwait) G35)
               (enable (G23 G34) G36)
               (enable (G33 G34) G37)
               (feared-what-would-do-next (Saudi-Arabia Saddam) G38)
               (feared-what-would-do-next (US Saddam) G39)
               (cause (G34 G38) G40)
               (cause (G34 G39) G41)
               (ask-help (emir-of-Kuwait US) G42)
               (ask-help (sheik-of-SA US) G43)
               (fight-for (US Kuwait) G44)
               (attack (US Iraq) G45)
               (cause (G39 G45) G46)
               (cause (G42 G45) G47)
               (cause (G43 G45) G48)
               (mobilize (Bush US) G49)
               (inspire (Bush US) G50)
               (order (Bush G45) G51)
;               (want (Bush G46) G52)
                (supplies (obj_supplies) G53)
                (provide (US Saudi-Arabia obj_supplies) G54)
                (bomb (US Iraq) G55)
                (missile (Iraq Saudi-Arabia) G56)
                (command (Bush US_forces) G57)
                (forces (US_forces) G57a)
                (has (US US_forces) G57b)
                (person (Schwarzkopf) G58)
                (general-of (Schwarzkopf Bush) G59)
                (lead (Schwarzkopf US_forces) G60)
                (mass-in (US_forces Saudi-Arabia) G61)
                (order (Saddam G34) G62)
                (beating (US Iraq) G63)
; why beating? weaker mobilized bomb command lead inspire mass
                (cause (G25 G63) G64)
                (cause (G49 G63) G65)
                (cause (G55 G63) G66)
                (cause (G60 G63) G67)
                (cause (G57 G63) G68)
                (cause (G61 G63) G69)
                (cause (G50 G63) G70)
                            )
               )                
) 
)

(defun make_WW2 ()

(make_struc 'WW2
            'sentence
            '(all
              ((country (Germany) W1)
               (country (US) W2)
               (country (England) W3)
               (country (France) W4)
               (country (Austria) W5)
               (country (Czechoslovakia) W6)
               (country (Poland) W7)
               (country (Japan) W8)
               (p_Germany (Germany) W9)
               (p_US (US) W10)
               (p_England (England) W11)
               (p_Czechoslovakia (Czechoslovakia) W12)
               (p_Poland (Poland) W13)
               (p_France (France) W14)
               (p_Austria (Austria) W15)
               (p_Japan (Japan) W16)
               (person (Hitler) W17)
               (person (FDR) W18)
               (person (Chamberlain) W19)
               (person (Churchill) W20)
               (person (leader-of-France) W21)
               (person (leader-of-Czechs) W22)
               (person (leader-of-Poles) W23)
               (person (leader-of-Austria) W24)
               (person (Hirohito) W200)
;   oops -- double-number error -- so Hirohito got high
               (leader-of (Hitler Germany) W25)
               (leader-of (FDR US) W26)
               (leader-of (Chamberlain England) W27)
               (leader-of (Churchill England) W28)
               (leader-of (leader-of-France France) W29)
               (leader-of (leader-of-Czechs Czechoslovakia) W30)
               (leader-of (leader-of-Poles Poland) W31)
               (leader-of (leader-of-Austria Austria) W32)
               (leader-of (Hirohito Japan) W33)
;don't need because of presumed
;               (dictator-of (Hitler Germany) W34)
;neighbor-of goes to Germany
               (neighbor-of (Austria Germany) W35)
               (neighbor-of (Czechoslovakia Germany) W36)
               (neighbor-of (Poland Germany) W37)
               (neighbor-of (France Germany) W38)
               (weaker-than (Austria Germany) W39)
               (weaker-than (Czechoslovakia Germany) W40)
               (weaker-than (Poland Germany) W41)
;ally-of goes weak to strong--change this for US/England
               (ally-of (France England) W42)
;               (ally-of (England France) W43)
               (ally-of (US England) W44)
;               (ally-of (England US) W45)
;               (ally-of (US France) W46)
               (ally-of (France US) W47)
               (ally-of (Japan Germany) W48)
;               (ally-of (Germany Japan) W49)
               
                (militarize (Hitler Germany) W50)
                (annex (Germany Austria) W51)
;                (take-first (Germany Austria) W52)
                (enable (W39 W51) W53)
                (enable (W50 W51) W53a)
                (order (Hitler W51) W54)

                (annex (Germany Czechoslovakia) W62)
                (enable (W40 W62) W63)
                (enable (W50 W62) W63a)
                (order (Hitler W62) W64)
                (feared-what-would-do-next (England Hitler) W73)
                (feared-what-would-do-next (France Hitler) W74)
                (cause (W62 W73) W75)
                (cause (W62 W74) W76)

                (attack (Germany Poland) W77)
                (order (Hitler W77) W78)
                (conquer (Germany Poland) W79)
                (enable (W41 W79) W80)
                (enable (W50 W79) W81)
                (fight-for (England Poland) W82)
                (order (Chamberlain W82) W83)
                (attack (England Germany) W86)
                (cause (W77 W86) W87)
                (cause (W73 W86) W88)
                (fight-for (France Poland) W89)
                (attack (France Germany) W90)
                (cause (W77 W90) W91)
                (cause (W74 W90) W92)

                (attack (Germany France) W100)
                (fight-for (England France) W101)
                (fight-for (France France) W102)
;though some would debate the above
                (conquer (Germany France) W104)
                (enable (W50 W104) W105)
                (enable (W96 W104) W106)
                (enable (W97 W104) W107)
                           
                (forces (English_forces) W107a)
                (forces (French_forces) W107b)
                (forces (US_forces) W107c)
                (has (England English_forces) W107d)
                (has (France French_forces) W107e)
                (has (US US_forces) W107f)

;next is the churchill part
                (inspire (Churchill England) W108)
                (militarize (Churchill England) W109)
                (ask-help (Churchill US) W110)
                (command (Churchill English_forces) W111)
                (command (Churchill French_forces) W112)
                (command (Churchill US_forces) W113)
                (person (Montgomery) W114)
                (general-of (Montgomery Churchill) W115)
                (lead (Montgomery English_forces) W116a) 
                (lead (Montgomery French_forces) W116b)
                (lead (Montgomery US_forces) W116c)
    
;now the minimalist us part
                (attack (Japan US) W117)
                (attack (US Japan) W118)
                (cause (W117 W118) W119)
                (declare-war-on (Germany US) W120)
                (attack (US Germany) W121)
                (cause (W120 W121) W122)
                (militarize (FDR US) W123)

                (conquer (England Germany) W124)
; why conquer? church inspired, eng mobilized, command, lead
                (cause (W108 W124) W125)
                (cause (W109 W124) W126)
                (cause (W116a W124) W127)
                (cause (W116b W124) W128)
                (cause (W116c W124) W129)
                (cause (W111 W124) W130)
                (cause (W112 W124) W131)
                (cause (W113 W124) W132)

 


              )
            )
)
)


